#Sources 
:sources: 
  Account: 
    :poll_interval: 300
 
:test: 
  :licensefile: settings/license.key
  :syncserver: http://localhost:9292/application/
  :redis: localhost:6379
:production: 
  :licensefile: settings/license.key
  :syncserver: http://localhost:9292/application/
  :redis: localhost:6379
:development: 
  :licensefile: settings/license.key
  :syncserver: http://localhost:9292/application/
  :redis: localhost:6379
