require 'rubygems'
require 'bundler/setup'

begin
  require 'vendor/rhosync/lib/rhosync/tasks'
  require 'vendor/rhosync/lib/rhosync'
rescue LoadError
  require 'rhosync/tasks'
  require 'rhosync'
end

ROOT_PATH = File.expand_path(File.dirname(__FILE__))

begin
  require 'resque/tasks'
  task "resque:setup" do
    require 'application'
  end
  desc "run rhosync console"
  task :console, :environment do |t, args|
    if RedisRunner.running?  
      #load development environment by default
      ENV['RACK_ENV'] = args[:environment] || 'development'
      sh "irb -rubygems -r rhosync -r console -r application"
    else
      puts "Redis is not running. Please start it by running 'rake redis:start' command."
    end
  end
rescue LoadError
  puts "Resque not available. Install it with: "
  puts "gem install resque\n\n"
end